### ISSUE TITLE
0.2.0-SNAPSHOT artifacts are not available

### ISSUE THREAD

**Issue by AlexanderShenshin** [eu-digital-identity-wallet/eudi-lib-android-iso18013-data-transfer#26]
Hi, thank you for your work!

I have a question regarding availability of older snapshot versions.

Recently, version 0.2.0-SNAPSHOT have been removed from `https://s01.oss.sonatype.org/` repository and this caused build issues in projects/demos that use older EUDI Android core versions (as this package is a transitive dependency).
Is it possible to bring this version back (re-publish) to make older setups work?

The question may sound strange as most straightforward way to deal with this is to just update EUDI reference dependencies, of course. But overall it will be nice to make sure that work that depends on older EUDI reference snapshots is not broken due to removed dependencies (or other problems that may appear over time).

**Comment by vkanellopoulos** [comment]
@AlexanderShenshin since the 0.2.0 version is released, the snapshot is removed automatically by maven. Please consider using the latest version of the core library `eu.europa.ec.eudi:eudi-lib-android-wallet-core:0.10.2`, found at https://github.com/eu-digital-identity-wallet/eudi-lib-android-wallet-core/tree/v0.10.2
